### ISSUE TITLE
スクレイピングの章についての指摘

### ISSUE THREAD

**Issue by takanory** [pyconjp/bootcamp-text#10]
- [ ] venv で環境を作ってから pip install する手順にしよう(自分の環境を汚さない
- [ ] sys.exit 必要?
- [ ] json で吐き出すのはやりたい人がやればよくて、とりあえずは対話的に先頭 X 件を print するくらいでいいんじゃないかな
- [ ] bs4 のコードがちょこっと複雑なので、もっとシンプルに取り出せるページを使ったほうがいいんじゃないかな。私が前使ったのは Python の ライブラリ一覧ページとか使った
- [ ] `# -- coding: utf-8 --` python 3 は default が utf-8 になったので、書かなくてよいはず(http://docs.python.jp/3/howto/unicode.html)
- [ ] argparse もやりたい人だけやればいいので、不要では

**Comment by Akira-Taniguchi** [comment]
http://bootcamp-text.readthedocs.io/5_scraping.html
こんな感じでやりました。
