### ISSUE TITLE
関数の例でrangeはいまいちかも

### ISSUE THREAD

**Issue by takanory** [pyconjp/bootcamp-text#12]
- range関数は 3 ではイテレーターを返すようになったので、リストが返らないので例としていまいちかも
- サンプルコードで for でループさせたりした方がよさそう
- http://bootcamp-text.readthedocs.io/1_intro.html#id16

**Comment by Akira-Taniguchi** [comment]
組み込み関数の例を示すのが目的だった箇所なので、もっと簡易に説明できるround関数に
変更しました。
