### ISSUE TITLE
5/27 リハーサルコメント(takanory)

### ISSUE THREAD

**Issue by takanory** [pyconjp/bootcamp-text#16]
- 最初に概要の説明するのよさそう
- みんなのレベル確認が必要だけど、アンケートで事前に確認した方がよさそう
- pyvenv→「パイブイエンブ」かなー
- リスト内包表記→「りすとないほうひょうき」
- コンソールはフォントでかくして表示しよう
- 例からkiyoharaとか削除したほうがよさそうw(元テキストの執筆者の名前)

モジュール

- 標準モジュールがたくさんあるよってのは実際にブラウザでみせてほしい

pyvenv

- pip と PyPI の話もセットでする必要がある。テキストにもうちょっと書いたほうがよさそう
- PyPI の画面をちゃんと見せてあげる
- Windowsでの activate/deactivate について追記したほうがよい

スクレイピング

- 今までやったことのまとめの実習としてスクレイピングをここではやるけど、他のことやりたい人はやってもいいよってことを説明してほしい
- beautifulsoupの使い方はもうちょっとテキストにほしい, find, findAll とかとか
- requests, beautifulsoup のドキュメントへのリンクがほしい
- `main()` を書いてもそのまま実行される。 `if __name__ == '__main__':` に入れると、モジュールとしてインポートされたときに実行されない
- 実習としては、同じコードやってもいいし、自分がスクレイピングしたいページからほしい情報を抜き出すとかやってもよい
- テキストに例としていい感じのページの例とか載せとくとよいかも

**Comment by ryu22e** [comment]
テキストの変更内容をリストアップしました。

pyvenv
- [ ] pip と PyPI の話もセットでする必要がある。テキストにもうちょっと書いたほうがよさそう
- [ ] Windowsでの activate/deactivate について追記したほうがよい

スクレイピング
- [ ] beautifulsoupの使い方はもうちょっとテキストにほしい, find, findAll とかとか
- [ ] requests, beautifulsoup のドキュメントへのリンクがほしい
- [ ] main() を書いてもそのまま実行される。 if __name__ == '__main__': に入れると、モジュールとしてインポートされたときに実行されない
- [ ] テキストに例としていい感じのページの例とか載せとくとよいかも

**Comment by takanory** [comment]
出来る範囲でやります

**Comment by takanory** [comment]
@ryu22e できるとこまでやった。windows は誰か確認して欲しい。最後のやつはまぁ、できそうならそのうちやる感じでいきたいので、別チケットにしてほしいかな。

**Comment by ryu22e** [comment]
>テキストに例としていい感じのページの例とか載せとくとよいかも

Issue #25 に分けました。

**Comment by ryu22e** [comment]
Windows版のpyenvの確認をしようと思って、テキストに載っている方法で、Python 3.5.1をインストールしたのですが、もしかして、pyenvは同梱されていない？(Windows/Python3.5使っていないので全く分からない…)
http://bootcamp-text.readthedocs.io/1_install.html#windows

どなたかご存じないでしょうか？

**Comment by takanory** [comment]
pyenv じゃなくて pyvenv (名前がまぎらわしいけど

**Comment by shimizukawa** [comment]
pyvenv は同梱されてますが、スクリプトが `C:\Python35\Tools\pyvenv.py` としてインストールされているので、実行には以下のいずれかの書き方が必要

```
C:\Python35\python.exe C:\Python35\Tools\pyvenv.py
```
or
```
C:\Python35\python.exe -m venv
```

パスが通ってれば以下のように書けるかな
```
python.exe C:\Python35\Tools\pyvenv.py
```
or
```
python.exe -m venv
```

**Comment by ryu22e** [comment]
あ、pyvenvですね。失礼しました。
pyvenvは以下にインストールされていました。

```
C:\Users\ユーザー名\AppData\Local\Programs\Python\Python35\Tools\scripts
```

以下コマンドで `pyvenv env` `source env/bin/activate` と同じことができるようなので、Windowsの場合は以下コマンドを実行するようテキストに追記しておきます。

```
$ python.exe -m venv env
$ env\Scripts\activate.bat
```

**Comment by ryu22e** [comment]
第一回までに必要な変更は終わったので閉じます。
