### ISSUE TITLE
5/27 リハーサルコメント（honeyoubun）

### ISSUE THREAD

**Issue by uyuta** [pyconjp/bootcamp-text#17]
普段はPHP/JavaScriptを使った開発をしていて、Pythonについてはほとんど触ったことがありません。
その立場でコメントをさせていただきます。

## Boot Campに求めるもの

求めるものとしては、「なぜpythonなのか」というところが知りたいです。
どういう使用目的であればpythonを選ぶべきなのか、pythonを選ぶメリットはなんなのか、
逆にpythonが向いていないことなど、
そのあたりを教えていただくことができれば、今後にpythonを使っていくという選択肢を選びやすくなります。

## 内容について

+ もう少し深い内容でも問題はない
+ 説明はなくても、サンプルコードはもっと多くてもよいかと
+ 今回の倍の時間をかけて行うのであれば、時間があまりませんか。

**Comment by takanory** [comment]
@ryu22e これは具体的にどのへんを対応するつもり?

**Comment by ryu22e** [comment]
@takanory 
↓この部分をテキストに入れたほうが良いかなと思っています。
>求めるものとしては、「なぜpythonなのか」というところが知りたいです。

**Comment by takanory** [comment]
@ryu22e それかー、特に理由なくね?ちょっと私は思いつかないので、なんか良い文章があったらよろしく。この辺になんかヒントあるかな
http://docs.python.jp/3/faq/general.html

**Comment by ryu22e** [comment]
自分で必要と言ったものの、良い文章が思いつきませんね… あんまり変なことも書けないし、なくてもチュートリアルができないわけでもないので、第一回までに必要なタスクからは外しましょう。
>求めるものとしては、「なぜpythonなのか」というところが知りたいです。

**Comment by ryu22e** [comment]
すみません、他に優先度が高い対応Issue増えてきたので、これは Close にさせてください :bow:
