### ISSUE TITLE
2016-05-27 のpython bootcampについて

### ISSUE THREAD

**Issue by yabuki** [pyconjp/bootcamp-text#18]
プログラマー向けであるという前提で

  自習できる人たちが集まっているという前提で、自習できない部分を補う。という考え方もあるのかなとは思いました。
  他の言語をやっている人たちが、 _*躓きそうな部分にこそ需要がある*_ とおもうのですが、いかがでしょうか。pythonらしい部分、強みで、独習で他言語からpythonにスイッチするときに困りそうな部分について、まとまっていると素晴らしいかと思います。もちろん、わざわざpythonのboot campに来るぐらいですから、平均以上のモチベーションがあると仮定しても良いかと思います。

また事前課題も、スキルと進度の振り分けに役立つでしょう。事前課題と一緒に、ブートキャンプに参加するにあたって5時間?で 学ぶゴールについて聞いておくのもいいかもしれません。

ある一定規模以上のpythonプログラムを書くために、クラス・モジュールの生成や配置、それらのテストやドキュメント生成のトピックも軽く触れて、リンク集などあっても良いのではと思います。どうせプロジェクトをpythonでやろうとなると調べることになるのですから。

あと、各所でセミナーを開くのであれば、既存の質問のQAはFAQで、まとめておいてもらえると同じ質問はしなくていいかと思うので、ご一考ください。

----------------------------------------------------------------------------------------------------------------------

プログラマー向けなら、最初から 型の概念や、イテレーター、ネームスペースなどを教えてもいいのでは?
あと最初からコメントを教えないのは仕様ですか?

pythonで、嵌りそうな所、たとえば /ではフロートでかえって // でないとintでかえらない
roundが5で切り捨てとか、あと ふつうは、pep8やpyflakeで書き方を揃える、ドキュメントの
書き方とか、unittestは、どれがいいのか。などなど

自分である規模のプログラムを書くにあたって、ぶつかりそうな罠を避ける方法があるといいなと

**Comment by ryu22e** [comment]
pep8について→ 他にも類似の指摘があったので Issue #39 に分けました。
コメントの書き方→ Issue #40 に分けました。

他にも色々指摘いただきましたが、どこまでPython Boot Campでどこまでサポートするかは難しいところですね。ある程度学習の最初の部分をサポートして、あとは独学でも進めるようになってもらう、というのが理想かと思いますが…

>あと、各所でセミナーを開くのであれば、既存の質問のQAはFAQで、まとめておいてもらえると同じ質問はしなくていいかと思うので、ご一考ください。

FAQというか、開催後に参加者から貰った質問を元に、テキストの内容をブラッシュアップしていくのがいいかと思っています。

ひとまず、このIssueはCloseにさせてください。ありがとうございました :bow:
