### ISSUE TITLE
5/27 リハーサルコメント(ryokamiya)

### ISSUE THREAD

**Issue by ryokamiya** [pyconjp/bootcamp-text#19]
- pythonのインデントの話をサラッと話しましたが、pep8っていうスタイルガイドがあるっていうのを紹介してもいいかも。python独特だと思うし。
- みんなのレベルに合わせて、スキップできそうなところをあらかじめ検討つけておくといいかも。例えばみんな何かしらのプログラミング経験者が揃っているなら、fizz buzzの例で数字の連番をprintする段階を飛ばしていきなりfizz buzz例の最終形態を見せるとか。
- （issueじゃないですが）話のスピード、みんながついてきているかの確認（「そろそろ手が止まってきているようなので、、」とか）、話しながらコマンドラインで実演できたりとか、すごく上手にやってもらったと思います。

**Comment by ryu22e** [comment]
>pythonのインデントの話をサラッと話しましたが、pep8っていうスタイルガイドがあるっていうのを紹介してもいいかも。python独特だと思うし。

Issue #39 に分けました。
