### ISSUE TITLE
5/27 リハーサルコメント (Kobayashi)

### ISSUE THREAD

**Issue by rarewin** [pyconjp/bootcamp-text#20]
本日はおつかれさまでした。
私は、普段は組み込みでCやらARMのアセンブラを書いてる感じです。
細かい点もありますが、以下にリハーサル中に書いてたメモを記載させていただきます。

## 導入

* サイトのフォントがほそくて見辛いような気がします……。
* デモのターミナルとフォントのサイズは考えた方がよいかも。 (一番下でコマンド打っても見辛いです)
  * フォントサイズについては、指摘あって途中で解決。
  * ターミナルを上下二分割して上の方でやるとかよろしいでしょうか?

## Pythonのデータ型（基本編）

* 以下が話題に上がりました。
  * '//' も教えてほしいかもです。
  * `round(0.5) -> 0` とかはおもしろかったです。
  * 「ヒアドキュメント」 [Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%92%E3%82%A2%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88#Python])

## Pythonのデータ型［コレクション編］

* リストの要素について、例が追加のみでしたが、removeくらいは例を示したほうが? (その後一覧はありましたが)
* リストと違いタプルは不変（immutable）な値という点について、実際にエラー出してみたりした方が理解が進みそうです。どう使い分けるとかの例もあるとうれしいかもです。
* 辞書について、他の参加者の方にツッコまれてましたが、イテレータの説明が軽くでもないと.items()とか受講者の経験分野によってはピンと来ないような、と思いました。
  
## モジュール

* classの話とか無い中、唐突に 「マッチオブジェクト」と出て来たのが気になりました。
* モジュールの書き方をもうちょっと掘り下げてもらえるとうれしいです。
  この後出てきた `if __name__ == '__main__':` とかのはなしともつながりますし。

## pyvenv

* もっとモジュールの作り方とかを掘り下げてからでないと、必要性がわからない気がしました。あと、私が今読んでる本だとvirtualenv使ってます……。
* Bashスクリプトとか出てきてますが、Windowsでもバッチファイルがあるとのことなので、それ用の説明も必要ではないでしょうか。

## その他

* すぐに理解出来た人用の練習問題をつくるという意見が出ましたが、それには大賛成です。
* Pythonを選択する理由が聞きたいという意見にも賛成です。

**Comment by ryu22e** [comment]
> Pythonのデータ型［コレクション編］
> 辞書について、他の参加者の方にツッコまれてましたが、イテレータの説明が軽くでもないと.items()とか受講者の経験分野によってはピンと来ないような、と思いました。

Issue #38 に分けました。

>pyvenv
>もっとモジュールの作り方とかを掘り下げてからでないと、必要性がわからない気がしました。あと、私が今読んでる本だとvirtualenv使ってます……。

他のIssueでも類似の指摘があったので、 #29 に分けました。

他に色々指摘がありますが、対応しきれなさそうなので、最低限必要と思われる上記だけ残して、このIssueは閉じます :bow:
