### ISSUE TITLE
5/27 リハーサルコメント (ymyzk)

### ISSUE THREAD

**Issue by ymyzk** [pyconjp/bootcamp-text#21]
## 全体
- テキスト内の表記揺れの統一
  - 例えば, "Bootcamp", "bootcamp", "Boot Camp"
- 各章をどのくらいの時間で進めるのか事前に決めておかないと, 時間内にイベントを終えることが難しそう
- 演習問題等で時間調整できる部分があると良さそう
- コラムの背景色が, 注意や警告のような印象を受ける

## Pythonをはじめよう
- (この章で書くべきかはわかりませんが) Python がどのような言語かを簡単に説明してもいいかもしれません
  - どういう用途で使われているのか?
  - よく比較される言語は何か?
    - プログラミング経験がある方を対象にするなら, 他の言語の比較があるとわかりやすそう
  - どういう特徴があるのか?
- Python 2 / 3 の違いについても簡単いふれておいた方が, 後で受講者が自分で調べ物をする際に役立ちそうです

## Pythonのデータ型（基本編）
- 巨大な整数演算もできることを示しておくと, Python らしさが少し出そうです.

## Pythonのデータ型［コレクション編］
- ［コレクション編］のかっこは表記揺れ?
- `繰り返し用変数` という言葉が聞き慣れません

## モジュール
- モジュールまたは関数しかインポートできないような印象を受けました
- "その他便利なモジュールについては、一部を「 standard-library 」で扱います。" -> リンク切れ?
- 余裕があれば...
  - 何がエクスポートされるのかの説明 (cf. C言語だとヘッダファイルが必要)
  - パッケージについての説明

## pyvenv
- virtualenv や pyenv 等との比較を少し述べておくと親切かも
- "次節では、それを使ってスクレイピングを行う方法を記述します。" -> pyvenv を使ってスクレイピングをするというのは, 何か変な感じ

## スクレイピング
- shebang を書いているが, `python simple.py` のように実行しているので, shebang はなくてもいいかも (おまじないは減らしたほうが良い)
- HTML の知識がある程度あることを前提にしてしまっているが, 少しくらいは説明したほうがいいかも

## 最後に
- ライブラリのインストール方法を説明できているので, 各分野の有名ライブラリ紹介等を少し入れてもいいかも?
- イベント終了後に何らかのサポートができる方法を考えたい
  - 京都会場では, [CAMPHOR-](https://camph.net) でイベント後のサポートが可能です

## 参考
PyLadies Kyoto でも使用した, Python でプログラミングに入門するための資料です.
- 資料: http://python-tutorial.camph.net / ソース: https://github.com/camphor-/python-tutorial
- 大体3時間程度かかる資料です
  - 開発環境は [Web 上のもの](https://c9.io)を使ったので, 開発環境整備の時間は含みません

**Comment by ryu22e** [comment]
イベント名の表記ゆれは"Boot Camp"に統一しましたが、他にもないか見てみます。

**Comment by ryu22e** [comment]
@Akira-Taniguchi 
「モジュール」の章の以下の指摘ですが、「 standard-library 」は何へのリンクなのでしょうか？
>"その他便利なモジュールについては、一部を「 standard-library 」で扱います。" -> リンク切れ?

**Comment by Akira-Taniguchi** [comment]
おそらくコピー元から持ってきた際の消し忘れだと思います。すみません。

**Comment by ryu22e** [comment]
表記ゆれがないかざっと見てみましたが、イベント名"Boot Camp"と括弧の全角半角の違いぐらいしか見当たらなかったので、表記ゆれに関してはこれでfixにします。

@Akira-Taniguchi 
「 standard-library 」のリンク切れはどう直せばいいのか分からなかったので、私の方では手を付けていません。こちらだけ修正お願いできますか？
他の指摘点にも色々指摘がありますが、「 standard-library 」の修正だけ終わったら、とりあえず第一回までに必要なテキスト修正は終わり、ということにしていいかと思います。

**Comment by Akira-Taniguchi** [comment]
@ryu22e 
対応しました、遅れてすみません。

**Comment by ryu22e** [comment]
第一回までに必要な変更は終わったので、一旦このIssueは閉じます。
その他の指摘点は別Issueに分けたので、後日どうするか検討しましょう。
