### ISSUE TITLE
受講者の方から直接メールでいただいた意見

### ISSUE THREAD

**Issue by Akira-Taniguchi** [pyconjp/bootcamp-text#23]
メールの内容を下記にそのまま記述

プログラミングを１からスタートする目的の受講者という立場で、
フィードバックをご連絡いたします。

＝＝＝＝＝＝

受講者対象が不明瞭だったため、下記2点いずれかであることを事前案内に明記すべき。
　　　１．ある程度他の言語をいじっているが、pythonを触ってみたい人
　　　２．対象がプログラム最初心者の場合は
　　　　　　　　　　　
　　　※１が対象であるなら、
　　　　　・データ型などについて、なんのことか説明が不足している。
　　　　　・ある程度必要な環境を事前構築しておくのであれば、
　　　　　　Ver.2とVer.3の切り替え方、インストール手順、
　　　　　　推奨するエディタ、開発環境など事前に有ってほしい。

・関数の説明について、インデントや、行を開けるといったことの開設については、
　網掛けなどで強調していただくと良い（他の言語に慣れているとわかりづらい特徴
　なので）

・FizzBuzzGameの実演の前にデータ型の説明があるべきでは？
　ーーー＞strをソースの中で使っているので。。。

・タプルの説明がわかりづらいので、詳しく教えてほしい

・受講者に手を動かせる実習を増やしたほうが理解が早い。

**Comment by ryu22e** [comment]
>受講者対象が不明瞭だったため、下記2点いずれかであることを事前案内に明記すべき。

Issue #36 に分けました。

>・関数の説明について、インデントや、行を開けるといったことの開設については、

Sphinxでインデント網掛けってできましたっけ？ できなくても説明は入れたほうが良さそうなので #37 に分けました。

>・FizzBuzzGameの実演の前にデータ型の説明があるべきでは？

FizzBuzzの前の章で文字列についての説明しているから十分のような気がするけど、どうなんでしょうね。 http://bootcamp-text.readthedocs.io/2_intro.html#id6
第二回でも同様の指摘があったら検討するということで、今回は修正対象から外しましょう。

>タプルの説明がわかりづらいので、詳しく教えてほしい

改善するとしたら以下の文でしょうが、私から見て改善点が正直見当たりませんね… :sweat: 
http://bootcamp-text.readthedocs.io/4_collections.html#id16
第二回でも同様の指摘があったら検討するということで、今回は修正対象から外しましょう。

**Comment by ryu22e** [comment]
テキスト修正に関するIssueは分けたので、このIssueは閉じます。
