### ISSUE TITLE
ライセンスの矛盾

### ISSUE THREAD

**Issue by ymyzk** [pyconjp/bootcamp-text#35]
ライセンスについて [LICENSE](https://github.com/pyconjp/bootcamp-text/blob/3de770cac6dcd698b1e1d48d62373695f029fa8d/LICENSE) ファイルでは CC0 となっていますが, [本文](https://github.com/pyconjp/bootcamp-text/blob/3de770cac6dcd698b1e1d48d62373695f029fa8d/source/0_about.rst) では CC-BY となっており矛盾しているようです.

**Comment by ryokamiya** [comment]
Complete
