### ISSUE TITLE
関数の説明について、インデントや、行を開けるといったことについての説明を強調

### ISSUE THREAD

**Issue by ryu22e** [pyconjp/bootcamp-text#37]
Issue #23 から分けた。

Sphinxでインデント網掛けはできないかもしれないので、できなければ文章で説明を入れる。

```
・関数の説明について、インデントや、行を開けるといったことの開設については、
　網掛けなどで強調していただくと良い（他の言語に慣れているとわかりづらい特徴
　なので）
```

**Comment by ryu22e** [comment]
Sphinxでインデントに網掛けはできなさそうです。

関数の説明に既に以下のように書いているので、さらに説明文を入れるのはくどい気がするので、このままにしてIssueは閉じます。

```
Python はブロック構造をインデント（通常は4つのスペース）で書きます。

C言語のように波括弧（{ }）で囲む必要はなく、インデント自体が文の構造となります。

add() 関数内の1行目のreturn文は関数の中身なので、インデントで字下げします。

関数を書き終わったときにも改行を入力してください（最後の入力が文として終了していない場合、プロンプトが3つのドット（...）になります）。
```
http://bootcamp-text.readthedocs.io/textbook/2_intro.html#id10

**Comment by shimizukawa** [comment]
> 関数の説明について、インデントや、行を開けるといったことの解説については、網掛けなどで強調していただくと良い

これと

> Sphinxでインデントに網掛けはできなさそうです。

これは話がずれてそう。

**Comment by ryu22e** [comment]
@shimizukawa はい、ありがとうございます。

**Comment by ryu22e** [comment]
テキストを変更しました。どなたかご意見あればご指摘お願いします。

**Comment by ryu22e** [comment]
特に指摘なさそうなので閉じます。
