### ISSUE TITLE
インストール方法のリンクが開かない

### ISSUE THREAD

**Issue by terapyon** [pyconjp/bootcamp-text#50]
connpassに記載のインストールガイドが表示されない。
http://bootcamp-text.readthedocs.io/1_install.html

**Comment by ryu22e** [comment]
新しいURLはこれですね。私が今対応できるのでやります。

http://bootcamp-text.readthedocs.io/textbook/1_install.html

**Comment by ryu22e** [comment]
connpassページを修正しておきました。
http://pyconjp.connpass.com/event/34564/
