### ISSUE TITLE
6.1.1. pipコマンドでいきなりpipのアップグレードを行っているのに違和感あり

### ISSUE THREAD

**Issue by terapyon** [pyconjp/bootcamp-text#56]
pip はアップグレードしておいたほうが良いので、バージョン確認し、その後アップグレードを行う流れにしたい。

その後、すぐにrequestsをインストールしているが、pyvenvを作ってからインストールしたほうが良いので、注意書きを入れる。

**Comment by terapyon** [comment]
確認いただき、よければCloseしてください。

**Comment by ryu22e** [comment]
`** 以下はpipコマンドのサンプルです **` の部分が恐らく太字にする意図だと思うのですが、余分はスペースが入っているせいで `**` がそのまま表示されています。ここだけ修正お願いします。他は問題ないです。

ソース: https://github.com/terapyon/bootcamp-text/commit/544991e3943c5c7f77d00cacd6b04bd3d6c61ccf#diff-daf4e8f6860b7e6b6e9c9bd056557b20R39
実際のテキスト: http://bootcamp-text.readthedocs.io/textbook/6_pyvenv.html#pip
