### ISSUE TITLE
2.7.4. 実際のコード のiterが不要

### ISSUE THREAD

**Issue by terapyon** [pyconjp/bootcamp-text#57]
リスト要素を、iterしているがその説明がない。
iterする必要がないと思うので、入れた理由を知りたい。

**Comment by terapyon** [comment]
この件、意図を確認いただき、問題なければ削除します。
意図が確認できなくても削除しますが・・。

**Comment by ryu22e** [comment]
履歴追ってみると谷口さんが書いたようなので谷口さんに聞いてみます。

**Comment by ryu22e** [comment]
特に意図はないようなので、削除してもらってOKとのことです。
