### ISSUE TITLE
WindowsのPATH設定について注意書きを入れる

### ISSUE THREAD

**Issue by terapyon** [pyconjp/bootcamp-text#66]

**Comment by terapyon** [comment]
以下をドキュメントのどこかに記載しておきたい。pipあたりで止まっていたので、周辺のコラムでいいかも。


「Add Python 3.5 to PATH」にチェックを入れておきましょう。自動的に必要な環境変数が設定されます。

とあるのでこのとおりインストールすれば問題ないはずですが、Win利用者さんがいる場合は念のため環境変数(PATH)を確認すると良いと思います。

**Comment by takanory** [comment]
@terapyon issueのタイトルをちゃんと書きましょう

**Comment by terapyon** [comment]
あれ？保存されていなかった。
