### ISSUE TITLE
linux,およびmacのインストール手順が正しいか、実際の環境で確認する

### ISSUE THREAD

**Issue by Akira-Taniguchi** [pyconjp/bootcamp-text#8]
件名のまま。
裏をとっていないので、環境を持っている人に確認して欲しい。

**Comment by ryu22e** [comment]
Ubuntu 16.04にPython3.5.1をインストールしたところ、Python3.5.1のインストールはできましたが、[LIST 3 Pythonのバージョン確認](http://bootcamp-text.readthedocs.io/1_install.html#id4)にある `python -V` で以下のメッセージが表示されます。
```
The program 'python' can be found in the following packages:
 * python-minimal
 * python3
Try: sudo apt install <selected package>
```

`python3 -V` なら `Python 3.5.1` が表示されます。

**Comment by ryu22e** [comment]
[OS Xでの場合](http://bootcamp-text.readthedocs.io/1_install.html#os-x)は手順通りにインストールできました。

**Comment by ryu22e** [comment]
Linuxでのインストールですが、pipが見当たりません。 `which pip` でも何も表示されません。

**Comment by shimizukawa** [comment]
テキスト見ずにコメントします。
もしubuntuなら、pythonインストール時にpipがインストールされないように仕組まれてます。別途python-pipのインストールが必要。

2016年6月3日(金) 21:22 Ryuji TSUTSUI <notifications@github.com>:

**Comment by ryu22e** [comment]
@shimizukawa 
テキストではUbuntu16.04を使う前提になっています。ということは、テキストにpython-pipをインストールする手順を追加する必要があるということですね。ありがとうございます。

**Comment by ryu22e** [comment]
こちらのUbuntu 16.04で `python -V` でインストールの確認ができない件ですが、 `python3 -V` に書き換えても良いのですが、`python` にパス通す方法をご存知の方いませんか？

https://github.com/pyconjp/bootcamp-text/issues/8#issuecomment-223315548

**Comment by shimizukawa** [comment]
以下のページをみると、 /usr/bin/python が Python-3.x を指すことはなさそうです。
https://wiki.ubuntu.com/Python/3

こんな解決方法が紹介されてました。
{code}
alias python=python3
{code}
http://askubuntu.com/questions/320996/make-default-python-command-to-use-python-3

**Comment by ryu22e** [comment]
@shimizukawa aliasしか方法がないのですね。素直にテキストのほうを `python3 -V` に書き換えたほうが良さそうな気がしますね。ありがとうございます。

**Comment by ryu22e** [comment]
@Akira-Taniguchi 
検証結果は以下のとおりです。

Mac→手順通りで問題ない
Linux→幾つか問題があったので、検証結果に合わせてテキストを変更した

テキストの内容を確認して、問題なければIssueをCloseするようお願いします。

**Comment by Akira-Taniguchi** [comment]
問題ないと判断したので、本issueをクローズします。
