### ISSUE TITLE
pyvenv について追記

### ISSUE THREAD

**Issue by takanory** [pyconjp/bootcamp-text#9]
* [ ] requests などをインストールするので venv 環境が必要
* [ ] python 3.5なので pyvenv がいいかな
* [ ] モジュールの後半か、章を追加してください
* [ ] pip についての説明もここに書くとよさそう

**Comment by Akira-Taniguchi** [comment]
モジュールの後半に追加しました。

**Comment by takanory** [comment]
共有した養成読本テキストの3章の3_virtualenvがあるので、そこを参考にしてください。 deactivate とかの説明がないのと、環境に入っている時と抜けた時で何が違うのかみたいな説明がほしいです。

virtualenvwrapper の説明は不要。
